In [2]:
# Python program

# Base class
class Object:
    def func1(self):
        print("Object name:phone")
        
# Derived class

class Brand(Object):
    def func2(self):
        print("Brand:apple")
        
# Driver's code
object = Brand()
object.func1()
object.func2()

Object name:phone
Brand:apple


In [ ]:
# MULTIPLE INHERITANCE

In [3]:
class Mother:
    mothername = ""
    
    def mother(self):
        print(self.mothername)
        
# Base class2

class Father:
    fathername = ""
    
    def father(self):
        print(self.fathername)
        
# Derived class

class Daughter(Mother, Father):
    def parents(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername) 
        
# Driver's code
s1 = Daughter()
s1.fathername = "mohan"
s1.mothername = "kumari"
s1.parents()


Father : mohan
Mother : kumari


In [ ]:
# HIERARCHIAL INHERITANCE

In [4]:
class student:
    def func1(self):
        marks=(98+78+86+56+84)/5
        print('marks',marks)
        
#Derived Class

class grade(student):
    def func2(self):
        print('A Grade')
        
object1=grade()
object1.func1()
object1.func2()

marks 80.4
A Grade


In [ ]:
#Hybrid Inheritance

In [6]:
class Car:
    def func1(self):
        print("DISPLAY phone Brands!!")
        
class c1(Car):
    def func2(self):
        print("1.vivo\n2.oppo\n3.apple\n")
        
class c2(Car):
    def func3(self):
        print("Expensive: apple")
        
class c3(c1,c2):
    def func4(self):
        print('phone')
        
# Driver's code
object = c3()
object.func1()
object.func2()
object.func3()

DISPLAY phone Brands!!
1.vivo
2.oppo
3.apple

Expensive: apple


In [ ]:
#Multilevel Inheritance

In [12]:
class Grandfather:
    
    def __init__(self, grandfathername):
        self.grandfathername = grandfathername
        
# Intermediate class

class Father(Grandfather):
    def __init__(self, fathername, grandfathername):
        self.fathername = fathername
        
        # invoking constructor of Grandfather class
        Grandfather.__init__(self, grandfathername)
    
# Derived class

class Son(Father):
    def __init__(self, sonname, fathername, grandfathername):
        self.sonname = sonname
        
        # invoking constructor of Father class
        Father.__init__(self, fathername, grandfathername)
        
    def print_name(self):
        print('Grandfather name :', self.grandfathername)
        print("Father name :", self.fathername)
        print("Son name :", self.sonname)
    
# Driver code
s1 = Son('gopal', 'manoharan', 'rajeev')
s1.print_name()


Grandfather name : rajeev
Father name : manoharan
Son name : gopal


In [14]:
Rate = { 'bottle' : 5, 'chair' : 1200, 'pen' : 50}
item = input('Enter the item: ')
try:
    print(f'The rate of {item} is {Rate[item]}')
except KeyError:
    print(f'The price of {item} is not found')

Enter the item: bottle
The rate of bottle is 5


In [15]:
try: 
    a = 5
    b = 5
    assert a != b
except AssertionError: 
       if a==b:
            print("TRUE")
print ("Success, no error!")


TRUE
Success, no error!


In [1]:
class Attributes(object):
    num = 5
    print(num)
try:
    object = Attributes()
    print (object.attribute)
except AttributeError:
    print ("Attribute Exception")

5
Attribute Exception


In [3]:
try:
    
    a=int(input("enter:"))
    Type=a[1]
except ValueError: #Two or more int elements given as inputs
    print("Error Handled!")

enter:1,8
Error Handled!


In [4]:
import numpy as np
try:
    a=[12,34,56,78,98]
    print(np.max(a))
except IndentationError:
    print(np.max(a))

98


In [5]:
def fun(a):
    if a < 4:
 
        # throws ZeroDivisionError for a = 3
        b = a/(a-3)
 
    # throws NameError if a >= 4
    print("Value of b = ", b)
 
try:
    fun(2)
    fun(5)
 
# note that braces () are necessary here for 
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")


Value of b =  -2.0
NameError Occurred and Handled


In [6]:
# re.findall()
import pandas as pd
import numpy as np
import re
str1='Hello 12 rt 78. Cowboy 23'
pattern = '\d+'

result = re.findall(pattern,str1)
print(result)

['12', '78', '23']


In [7]:
#re.split()
string='twelve:12 Eighty nine:89 fourty:40'
pattern='\s+'

#maxsplit = 1
#split only at the first occurence

result = re.split(pattern,string,1)
print(result)


['twelve:12', 'Eighty nine:89 fourty:40']


In [8]:
#re.sub()
s1='abc 12\ de 23 \n f45 6'

 # matches all whitespace characters
pattern='\s+'

#empty string
replace = '\t&&\t' # && denotes white spaces

new = re.sub(pattern,replace,s1)
print(new)

abc	&&	12\	&&	de	&&	23	&&	f45	&&	6


In [9]:
#re.search()
s2='Python is Craze'
#check if python is beginning
match = re.search('\APython',s2)
m1=s2[0:6]

if match:
    print('Pattern found inside the string')
    print('Index:',m1)
else:
    print('Pattern not found!!')
   

Pattern found inside the string
Index: Python


In [13]:
import numpy as np
#one-dim
l=np.random.randint(23,98,66)
l


array([56, 74, 32, 33, 48, 55, 33, 64, 78, 68, 73, 27, 51, 38, 43, 48, 60,
       51, 86, 48, 39, 84, 68, 83, 47, 33, 32, 52, 72, 59, 23, 93, 51, 43,
       55, 43, 62, 44, 67, 72, 52, 31, 76, 31, 86, 54, 30, 83, 47, 41, 52,
       51, 77, 79, 26, 25, 68, 31, 56, 67, 85, 91, 23, 71, 83, 86])

In [14]:
#Sum
np.sum(l)

3690

In [15]:
 #max
np.max(l)

93

In [16]:
#multi-Dim
M=np.random.randint(10,40,(3,4))
M

array([[10, 34, 29, 16],
       [33, 35, 24, 31],
       [36, 28, 11, 27]])

In [17]:
#sum
print(np.sum(M,axis=1))
print(np.sum(M,axis=0))

[ 89 123 102]
[79 97 64 74]


In [18]:
#max
print('Max',np.max(M,axis=1))
print('Min',np.min(M,axis=0))


Max [34 35 36]
Min [10 28 11 16]


In [19]:
#Prod
l1=np.random.randint(10,20,3)
print(l1)
prod=np.prod(l1)
prod


[17 13 12]


2652

In [20]:
#Mean
mean=np.mean(l1)
print(l1)
print(mean)

[17 13 12]
14.0


In [21]:
#std
l2=np.random.randint(10,20,3)
print(l2)
std=np.std(l2)
print(std)

[15 16 18]
1.247219128924647


In [22]:
 #any
a=[0,8,0]
np.any(a) 

True

In [23]:
#all
x=[2,4,6,0,8]
np.all(x)

False

In [24]:
#Median
x=list((12,45,67,89,90))
print(x)
med=np.median(x)
print(med)

[12, 45, 67, 89, 90]
67.0


In [25]:
#Masking
import numpy.ma as ma
m = np.zeros(4)
m
x=np.array([0., 0., 0., 0.])
ma.make_mask(m)
False
ma.make_mask(m, shrink=False)
np.array([False, False, False, False])

array([False, False, False, False])

In [26]:
#Comparisons
# <
a=np.array([12,45,67,34,90,34])
print(a)
x=a<40
print('1.',x)
# >
print('\n2.',a>40)
# ==
print('\n3.',a==45)
# <=
print('\n4.',a<=40)
# >=
print('\n5.',a>=40)
# !=
print('\n6.',a!=67)


[12 45 67 34 90 34]
1. [ True False False  True False  True]

2. [False  True  True False  True False]

3. [False  True False False False False]

4. [ True False False  True False  True]

5. [False  True  True False  True False]

6. [ True  True False  True  True  True]


In [27]:
 bool(42),bool(0)

(True, False)

In [28]:
bool(42 and 0)

False

In [29]:
bool(42 or 0)

True

In [30]:
bin(55)


'0b110111'

In [31]:
bin(0)


'0b0'

In [32]:
bin(55 & 0)

'0b0'

In [33]:
bin(55 | 0)

'0b110111'

In [34]:
bin(55|2)

'0b110111'